version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt
      - ./requirements.dev.txt:/app/requirements.dev.txt
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - OPENSEARCH_ENDPOINT=${OPENSEARCH_ENDPOINT}
      - PYTHONPATH=/app
    # 컨테이너가 계속 실행되도록 설정
    command: tail -f /dev/null