version: '3.8'

services:
  rag:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - OPENSEARCH_ENDPOINT=${OPENSEARCH_ENDPOINT} 